### ISSUE TITLE
Using hidesNavigationBarDuringPresentation results in wrong frame

### ISSUE THREAD

**Issue by RickiG** [stuartbreckenridge/UISearchControllerWithSwift#3]
If I set this to true:
*controller.hidesNavigationBarDuringPresentation = true*
The searchBar is displayed outside of the parent frame.

**Comment by stuartbreckenridge** [comment]
If using `controller.hidesNavigationBarDuringPresentation = true`
add the following line:
`self.definesPresentationContext = true`

**Comment by RickiG** [comment]
Thanks, just spend 1 hour fiddling with the layout of my searchBar:)
