### ISSUE TITLE
Cannot assign value of type 'SearchViewController' to type 'UISearchResultsUpdating?'

### ISSUE THREAD

**Issue by Grimbode** [stuartbreckenridge/UISearchControllerWithSwift#4]
tvOS application is causing this error in my `class SearchViewController: UIViewController {...}`

```
override func viewDidLoad() {
        super.viewDidLoad()
        
        // Configure countryTable
        countryTable.tableHeaderView = countrySearchController.searchBar

        //This line here is causing the error
        countrySearchController.searchResultsUpdater = self
    }
```

How do I fix this? Thanks.

**Comment by Grimbode** [comment]
Guess it was a silly mistake. I had to add UISearchResultsUpdating, which wasn't shown in the example. Bug?
`class SearchViewController: UIViewController, UISearchResultsUpdating {...}`

**Comment by stuartbreckenridge** [comment]
In the extensions file: https://github.com/stuartbreckenridge/UISearchControllerWithSwift/blob/master/SearchController/ViewControllerExtensions.swift
